reservch/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views
from myapp.views import MakeReservation,RetryPayment
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('<uuid:uuid>', views.index, name="index"),
    path('<uuid:user_uuid>/make_reservation/', csrf_exempt(MakeReservation.as_view()), name='make_reservation'),
    path('form_error/<uuid:uuid>/', views.form_error, name='form_error'),
    path('form_success/<uuid:reservation_uuid>/', views.form_success, name='form_success'),
    path('stripe_webhook/', views.stripe_webhook, name='stripe-webhook'),
    path('retry_payment/<uuid:reservation_uuid>/', RetryPayment.as_view(), name='retry_payment'),
    path('dashboard/courses/', views.courses, name='courses'),
    path('dashboard/courses/historique', views.historique, name='historique'),
    path('dashboard/setting/', views.setting, name='setting'),
    path('dashboard/other_settings/', views.other_settings, name='other_settings'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/update-reservation/', views.update_reservation, name='update_reservation'),
    # path('update_vehicle_type/<int:pk>/', views.update_vehicle_type, name='update_vehicle_type'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
# Create your models here.
from django.db import models
import uuid
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from django.dispatch import receiver

from datetime import time

class CustomUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, null=True)
    url_website = models.CharField(max_length=200, blank=True, null=True)
    online_payment = models.BooleanField(default=True)
    cash_payment = models.BooleanField(default=True)
    stripe_public_key = models.CharField(max_length=200, blank=True, null=True)
    stripe_secret_key = models.CharField(max_length=200, blank=True, null=True)
    google_maps_key = models.CharField(max_length=200, blank=True, null=True)
    notifications_active = models.BooleanField(default=False)


    online_payment_start_time = models.TimeField(default=time(1, 0))  # 01:00
    online_payment_end_time = models.TimeField(default=time(6, 0))    # 06:00

class VehicleType(models.Model):
    VEHICLE_CHOICES = [
        ("economique", "Économique"),
        ("berline", "Berline"),
        ("premium", "Premium"),
        ("van", "Van"),
        ("minibus", "Minibus"),
    ]

    name = models.CharField(max_length=50, choices=VEHICLE_CHOICES)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="vehicle_types")
    active = models.BooleanField(default=True)
    cost_per_km = models.DecimalField(max_digits=5, decimal_places=2, default=1.5)
    cost_per_minute = models.DecimalField(max_digits=5, decimal_places=2, default=0.20)
    minimum_cost = models.DecimalField(max_digits=5, decimal_places=2,default=20)
    night_fare_increase = models.IntegerField(default=10)  
    night_start_time = models.TimeField(default=time(0, 0))  # 00:00
    night_end_time = models.TimeField(default=time(5, 0)) 
    orly_fare = models.DecimalField(max_digits=5, decimal_places=2, null=True, default=70)
    cdg_fare = models.DecimalField(max_digits=5, decimal_places=2, null=True, default=50)
    seats = models.IntegerField(default=4)
    baggage = models.IntegerField(default=2)

@receiver(post_save, sender=CustomUser)
def create_vehicle_types(sender, instance, created, **kwargs):
    if created:
        for vehicle_type in VehicleType.VEHICLE_CHOICES:
            VehicleType.objects.create(name=vehicle_type[0], user=instance)

class Reservation(models.Model):
    CustomUser = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, null=True)
    PICKUP = 'PU'
    DESTINATION = 'DE'
    ADDRESS_TYPES = [
        (PICKUP, 'Pickup'),
        (DESTINATION, 'Destination'),
    ]
    
    # Address
    from_place = models.CharField(max_length=255, verbose_name="Lieu de prise en charge")
    to_place = models.CharField(max_length=255, verbose_name="Destination")
    step_place = models.CharField(max_length=255, verbose_name="Etape" , null=True, blank=True)

    #Go and back
    is_round_trip = models.BooleanField(default=False, verbose_name="Aller-retour", null=True, blank=True)
    step_on_return = models.BooleanField(default=False, verbose_name="Avec étape au retour", null=True , blank=True)

    # Date and time
    reservation_date = models.DateField(verbose_name="Date de réservation", null=True)
    reservation_time = models.TimeField(verbose_name="Heure de réservation", null=True)

    # Vehicle
    vehicle_type = models.CharField(max_length=20, choices=[
        ('economique', 'Economique'),
        ('berline', 'Berline'),
        ("premium", "Premium"),
        ('van', 'Van'),
        ("minibus", "Minibus"),
    ], verbose_name="Type de véhicule")
    
    # User info
    name = models.CharField(max_length=255, verbose_name="Nom")
    first_name = models.CharField(max_length=255, verbose_name="Prénom")
    phone_number = models.CharField(max_length=20, verbose_name="Numéro de téléphone")
    email = models.EmailField(verbose_name="Email")

    # Additional info
    passengers = models.IntegerField(verbose_name="Nombre de passagers")
    vol = models.CharField(max_length=255, verbose_name="Numéro de réservation", null=True, blank=True,)
    assistance = models.CharField(max_length=255, verbose_name="Assistance", null=True, blank=True,)
    special_requests = models.TextField(null=True, blank=True, verbose_name="Demandes spéciales")
    
    # Payment
    payment_method = models.CharField(max_length=20, choices=[
        ('cash', 'Sur place'),
        ('online', 'En ligne')
    ], verbose_name="Méthode de paiement")
    payment_status = models.BooleanField(default=False, verbose_name="Statut du paiement")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Prix", null=True)
    stripe_session_id = models.CharField(max_length=255, null=True, blank=True, verbose_name="Stripe Session ID")
    reservation_id = models.CharField(max_length=5, unique=True, verbose_name="ID de Réservation", null=True)
    
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Date de création")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Date de mise à jour")

    # Status
    IN_PROGRESS = 'IP'
    COMPLETED = 'CP'
    STATUS_CHOICES = [
        (IN_PROGRESS, 'En cours'),
        (COMPLETED, 'Complété'),
    ]
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=IN_PROGRESS, verbose_name="Statut")

    class Meta:
        verbose_name = "Réservation"
        verbose_name_plural = "Réservations"

    def __str__(self):
        return f"{self.name} {self.first_name} - {self.from_place} à {self.to_place}"

myapp/forms.py
from django import forms
from .models import Reservation

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = [
            'from_place', 'to_place', 'vehicle_type',
            'name', 'first_name', 'phone_number', 'email',
            'passengers', 'special_requests',
            'payment_method', 'stripe_session_id',
            'reservation_date', 'reservation_time', 'price',
            'vol', 'assistance', 'step_place', 'is_round_trip', 'step_on_return'
        ]

myapp/views.py
import uuid
import stripe
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.http import JsonResponse
from django.views import View
from .forms import ReservationForm
from .models import *
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.contrib import messages
from datetime import datetime, timedelta
from decimal import Decimal, InvalidOperation
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.db import transaction

import logging

logger = logging.getLogger(__name__)


# stripe.api_key = settings.STRIPE_SECRET_KEY
# Create your views here.


def convert_time_to_24h(time_obj):
    return time_obj.strftime("%H:%M")


def index(request, uuid):
    custom_user = get_object_or_404(CustomUser, uuid=uuid)

    vehicle_types = VehicleType.objects.filter(user=custom_user, active=True).values()
    
    vehicle_types_list = list(vehicle_types)
    
    for vehicle_type in vehicle_types_list:
        vehicle_type['night_start_time'] = convert_time_to_24h(vehicle_type['night_start_time'])
        vehicle_type['night_end_time'] = convert_time_to_24h(vehicle_type['night_end_time'])
    
    now_time = datetime.now().time()
    if custom_user.online_payment_start_time < custom_user.online_payment_end_time:
        show_online_payment = custom_user.online_payment and (custom_user.online_payment_start_time <= now_time <= custom_user.online_payment_end_time)
    else:
        show_online_payment = custom_user.online_payment and (custom_user.online_payment_start_time <= now_time or now_time <= custom_user.online_payment_end_time)
    
    context = {
        'uuid': uuid,
        'user_uuid': uuid,
        'stripe_public_key': custom_user.stripe_public_key,
        'google_maps_key': custom_user.google_maps_key, 
        'vehicle_types': vehicle_types_list, 
        'show_online_payment': show_online_payment,
        'show_cash_payment': custom_user.cash_payment,  
    }
    return render(request, 'form.html', context)

@login_required(login_url='login')
def courses(request):
    if request.user.is_authenticated:
        custom_user = CustomUser.objects.get(user=request.user)
        
        
        user_reservations = Reservation.objects.filter(CustomUser=custom_user, status=Reservation.IN_PROGRESS).order_by('-created_at')

        

        today = datetime.now().date()
        tomorrow = today + timedelta(days=1)

        for reservation in user_reservations:
            reservation_date = reservation.reservation_date
            if reservation_date == today:
                reservation.display_date = "Aujourd'hui"
            elif reservation_date == tomorrow:
                reservation.display_date = "Demain"
            else:
                reservation.display_date = reservation_date.strftime("%d/%m/%Y")


        context = {
            'user_reservations': user_reservations,
            'custom_user' : custom_user
        }
        return render(request, 'dashboard/courses.html', context)



@login_required(login_url='login')
def setting(request):
    vehicle_types = ["Économique", "Berline", "Premium", "Minibus", "Van"]
    with transaction.atomic():
         user_settings = CustomUser.objects.select_for_update().get_or_create(user=request.user)[0]
         custom_user = CustomUser.objects.get(user=request.user)
     
         if request.method == 'POST':
             form_type = request.POST.get('form_type')
             if form_type == 'payment_method':
                 user_settings.online_payment = 'online_payment' in request.POST
                 user_settings.cash_payment = 'cash_payment' in request.POST
                 
                 online_payment_start_time = request.POST.get('online_payment_start_time')
                 online_payment_end_time = request.POST.get('online_payment_end_time')
                 
                 if online_payment_start_time and online_payment_end_time:  
                     user_settings.online_payment_start_time = online_payment_start_time
                     user_settings.online_payment_end_time = online_payment_end_time
             
                 
                 user_settings.save()
     
     
             elif form_type == 'redirection_url':
                 user_settings.url_website = request.POST.get('url_website')
                 user_settings.save()
                 messages.success(request, 'URL de redirection mise à jour avec succès !')
     
             elif form_type == 'vehicle_type':
                  for vehicle_type in user_settings.vehicle_types.all():
                      vehicle_type_form_prefix = vehicle_type.name  
          
                      try:
                          vehicle_type.active = f"{vehicle_type_form_prefix}_active" in request.POST
                          vehicle_type.cost_per_km = Decimal(request.POST.get(f"{vehicle_type_form_prefix}_cost_per_km", "0"))
                          vehicle_type.cost_per_minute = Decimal(request.POST.get(f"{vehicle_type_form_prefix}_cost_per_minute", "0"))
                          vehicle_type.minimum_cost = Decimal(request.POST.get(f"{vehicle_type_form_prefix}_minimum_cost", "0"))
                          vehicle_type.night_fare_increase = Decimal(request.POST.get(f"{vehicle_type_form_prefix}_night_fare_increase", "0"))
                          vehicle_type.night_start_time = request.POST.get(f"{vehicle_type_form_prefix}_night_start_time")
                          vehicle_type.night_end_time = request.POST.get(f"{vehicle_type_form_prefix}_night_end_time")
                          vehicle_type.orly_fare = Decimal(request.POST.get(f"{vehicle_type_form_prefix}_orly_fare", "0"))
                          vehicle_type.cdg_fare = Decimal(request.POST.get(f"{vehicle_type_form_prefix}_cdg_fare", "0"))
          
                          if not(vehicle_type.night_start_time and vehicle_type.night_end_time):
                              raise ValueError("Invalid time values")
          
                          vehicle_type.save()
                          
                      except InvalidOperation:
                          continue  
                      except ValueError as e:
                          continue
          
                  messages.success(request, 'Paramètres mis à jour avec succès !')
                  return redirect('setting')
     
         context = {
             'custom_user': custom_user,
             'vehicle_types': vehicle_types,
             'user_settings': user_settings,
             'vehicle_types': user_settings.vehicle_types.all(),
         }
    return render(request, 'dashboard/setting.html', context)


@login_required(login_url='login')
def other_settings(request):
    custom_user = CustomUser.objects.get(user=request.user)
    with transaction.atomic():
        user_settings = CustomUser.objects.select_for_update().get_or_create(user=request.user)[0]
        
        if request.method == 'POST':
            form_type = request.POST.get('form_type')

            if form_type == 'api_keys':
                user_settings.stripe_public_key = request.POST.get('stripe_public_key')
                user_settings.stripe_secret_key = request.POST.get('stripe_secret_key')
                user_settings.google_maps_key = request.POST.get('google_maps_key')

            elif form_type == 'notifications':
                user_settings.notifications_active = 'notifications_active' in request.POST

            user_settings.save()
            messages.success(request, 'Paramètres mis à jour avec succès !')
            return redirect('other_settings')

    context = {
        'user_settings': user_settings,
        'custom_user' : custom_user
               }
    return render(request, 'dashboard/other_settings.html', context)

class MakeReservation(View):
    def post(self, request, user_uuid, *args, **kwargs):

        try:
            custom_user = CustomUser.objects.get(uuid=user_uuid)
        except CustomUser.DoesNotExist:
            return JsonResponse({'error': 'User not found'}, status=404)

        is_round_trip = request.POST.get('is_round_trip', 'No') == 'Yes'
        step_on_return = request.POST.get('step_on_return', 'No') == 'Yes'

        form = ReservationForm(request.POST)
        print(request.POST)
        if form.is_valid():
            reservation_id = str(uuid.uuid4())[:5]
            reservation = form.save(commit=False)
            
            reservation.CustomUser = custom_user  
            reservation.reservation_id = reservation_id
            
            reservation.is_round_trip = is_round_trip
            reservation.step_on_return = step_on_return
            
            reservation.save()

            reservation_data = {
                'reservation_id': reservation.reservation_id,
                'name': reservation.name,
                'first_name': reservation.first_name,
                'phone_number': reservation.phone_number,
                'email': reservation.email,
                'from_place': reservation.from_place,
                'to_place': reservation.to_place,
                'step_place': reservation.step_place,
                'is_round_trip': reservation.is_round_trip,
                'step_on_return': reservation.step_on_return,
                'vehicle_type': reservation.vehicle_type,
                'vol': reservation.vol,
                'assistance': reservation.assistance,
                'passengers': reservation.passengers,
                'special_requests': reservation.special_requests,
                'payment_method': reservation.payment_method,
                'price': reservation.price,
                'reservation_date': reservation.reservation_date.strftime('%d %B %Y'),

myapp/templates/form_success.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;1,200&display=swap" rel="stylesheet">
    <title>Confirmation</title>
    <style>
        body {
            font-family:roboto;
            color: #555;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            margin: 0;
            font-size: 13px;
        }
        .confirmation-card {
            background: #fff;
            border-radius: 10px;
            overflow: hidden;
            width: 80%;
            max-width: 400px;
            transform: scale(0.9);
            animation: enter 0.5s forwards;
            border: solid 1px #000000;
            margin-top: 40px;
            margin-bottom: 40px;
        }
        @keyframes enter {
            to {
                transform: scale(1);
            }
        }
        .header {
            background-color: #000000;
            color: #fff;
            padding: 20px;
            text-align: center;
            font-size: 18px;
        }
        .details {
            padding: 20px;
        }
        .detail {
            border-bottom: 1px solid #eee;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .detail:last-child {
            border-bottom: none;
        }
        .footer {
            background-color: #000000;
            color: #fff;
            padding: 20px;
            text-align: center;
        }
        i {
            margin-right: 10px;
            color: #4CAF50;
        }

        .detail-1 {
            border-bottom: 1px solid #eee;
            padding: 10px;
        }
        .detail-2 {
            display: flex;
            align-items: center;
            border-bottom: 1px solid #eee;
            padding: 10px 0px 20px 0px;
        }
        
        img.roadmap2 {
            width: 20px;
            margin-right: 15px;
        }      
        a.download-btn {
            color: #4caf50;
        }

        h1 {
            font-size: 20px;
        }
    </style>
</head>
<body>
    <div class="confirmation-card">
        <div class="header">
            <h1>Réservation envoyer</h1>
            <p style="font-size: 13px;">Un agent vous contactera ou vous recevrez un message dans un instant pour confirmer les détails de votre course.</p>
        </div>
        <div class="details">
            <div class="detail-2">
                <div>
                    {% if reservation.step_place %}
                        <img style="width: 23px" class="roadmap2" src="{% get_static_prefix %}img/roadmapstep2.png" alt="">
                    {% else %}
                        <img class="roadmap2" src="{% get_static_prefix %}img/roadmap1.png" alt="">
                    {% endif %}
                </div>
                <div>
                    <span>{{ reservation.from_place }}</span><br><br>
                    {% if reservation.step_place %}
                        <span>{{ reservation.step_place }}</span><br><br>
                    {% endif %}
                    <span>{{ reservation.to_place }}</span>
                </div>
            </div>
            <div class="detail">
                <span>Type de transfert</span>
                {% if reservation.is_round_trip %}
                    {% if reservation.step_on_return %}
                        <span>Aller-retour avec étape au retour</span>
                    {% else %}
                        <span>Aller-retour</span>
                    {% endif %}
                {% else %}
                    <span>Aller simple</span>
                {% endif %}
            </div>
            <div class="detail">
                <span>Date & Heure</span>
                <span>{{ reservation.reservation_date|date:"d/m/Y" }} à {{ reservation.reservation_time|time:"H\hi" }}</span>
            </div>
            <div class="detail">
                <span>{{ reservation.get_vehicle_type_display }}</span>
                <span>{{ reservation.passengers }} passagers</span>
            </div>
            {% if reservation.special_requests %}
            <div class="detail">
                <span>Demandes spéciales</span>
                <strong>{{ reservation.special_requests }}</strong>
            </div>
            {% endif %}
            <div class="detail">
                <span>{{ reservation.name }}</span>
                <span>{{ reservation.first_name }}</span>
            </div>
            <div class="detail">
                <span>{{ reservation.email }}</span>
                <span>{{ reservation.phone_number }}</span>
            </div>  
            <div class="detail">
                <span>
                    {{ reservation.get_payment_method_display }}
                    {% if invoice_url %}
                    <div class="invoice-download">
                        <a href="{{ invoice_url }}" class="download-btn" target="_blank">Télécharger la facture</a>
                    </div>
                    {% endif %}
                </span>
                <strong style="color: #000000;">{{ reservation.price }}€</strong>

            </div>
        </div>
        <div class="footer">
            <p style="font-size:15px;">ID de Réservation: <strong>{{ reservation.reservation_id }}</strong></p>
            <div class="cta">
                <p>Merci pour votre réservation ! </p>
                <a href="{% url 'index' uuid=uuid %}" class="return-btn">Retourner à l'Accueil</a>
            </div>
        </div>

    </div>
</body>
</html>

myapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connexion au Tableau de Bord des Réservations</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="styles.css">
</head>
<style>
    body {
        font-family: roboto;
    }
    
    .login-panel {
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
    }
    
    .card-header {
        border-bottom: none;
    }
    
    .btn-dark {
        background-color: black;
        border-color: #000;
    }

    .bg-dark {
        background-color: #000000!important;
    }
    
    .btn-dark:hover {
        background-color: #333;
    }
    
</style>
<body>
    <div class="container">
        <div class="row justify-content-center align-items-center vh-100">
            <div class="col-md-4">
                <div class="login-panel card">
                    <div class="card-header bg-dark text-white">
                        <h3>Connexion </h3>
                    </div>
                    <div class="card-body">
                        <form  method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username"></label>
                                <input type="text" class="form-control" id="username" name="username" placeholder="Nom d'utilisateur"required>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" id="password" name="password" placeholder="Mot de passe" required>
                            </div>
                            <br>
                            <button type="submit" class="btn btn-dark">Se connecter</button>
                        </form>
                        {% if messages %}
                        <br>
                            {% for message in messages %}
                                <span{% if message.tags %} style="color:red;" class="{{ message.tags }}"{% endif %}>{{ message }}</span>
                            {% endfor %}
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>